name: Deploy Chatbot to Hugging Face Spaces

on:
  push:
    branches:
      - main
    paths:
      - "chatbot/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git --version
          which git

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          git clone https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/Revochatbot ./space
          cp -r ./chatbot/* ./space/
          cd ./space
          git add .
          git commit -m "Deploy chatbot from GitHub Actions" --allow-empty
          git push
